version: '3'
services:
  postgres:
    image: postgres:13
    container_name: containername
    environment:
      POSTGRES_USER: your user
      POSTGRES_PASSWORD: your password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: